### ISSUE TITLE
vkTests SIGABORT on instance destructor

### ISSUE THREAD

**Issue by Jerboa-app** [JerboaBurrow/jGL#30]
```
#3  0x00007ffff7642476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff76287f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff7f61f40 in vkDestroyDescriptorSetLayout ()
   from /lib/x86_64-linux-gnu/libvulkan.so.1
#6  0x00005555558c96bf in jGL::Vulkan::Pipeline::~Pipeline (this=0x555556ccf850
```

**Comment by Jerboa-app** [comment]
the particles demo runs perfectly in vulkan

**Comment by Jerboa-app** [comment]
text renderer, a unique ptr to it, was destructed as expected as it goes out of scope.

But it goes out of scope after the vulkan c api has already been destructed...

fixed by manually resetting the unique ptr before those destructor calls
